### PR TITLE
Handle more than one DistrictAdminUser

### PR DESCRIPTION
**Pull request by imsickofmaps**
Sentry: http://prd-sentry.za.prk-host.net/rts/rts-zambia/group/44872/

url = https://www.zambiaschoolgateway.com/admin/data/teacherperformancedata/add/ 

MultipleObjectsReturned: get() returned more than one DistrictAdminUser -- it returned 4! Lookup parameters were {'district': <District: Solwezi>}

Check: https://www.zambiaschoolgateway.com/admin/data/districtadminuser/

### CODE REVIEW

**Comment by imsickofmaps** [comment]
@gsvr review please

**Comment by gsvr** [comment]
:+1:

**Pull request merged**
